language: cpp
before_install: sudo apt-get update
install: sudo apt-get install git build-essential libssl-dev libboost-all-dev libdb++-dev libminiupnpc-dev qt-sdk -y
script: cd src && make -f makefile.unix USE_UPNP=0 && cd .. && qmake "USE_UPNP=0" && make
